/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Algoritmos.NodoGrafo;
import Algoritmos.Grafo;
import java.awt.Color;
import static java.awt.Color.WHITE;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.util.ArrayList;
import java.util.HashSet;

/**
 *
 * @author rafae
 */
public class MostrarGrafo extends javax.swing.JPanel {
    private Grafo grafoMuestra;
    private int radioNodo = 25;
    private int tamañoGrafo;
    private int[][] matrizAdyacencia;
    private ArrayList<NodoGrafo> listaNodos;
    private int[] listaColores = new int[tamañoGrafo];
    private String nombreAlgo;
    private int cantColores;

    // obtener titulo del algoritmo de un int
    public static String getNameAlgorithm(int numAlgo) {
        return switch (numAlgo) {
            case 1 -> "Greedy";
            case 2 -> "Welsh-Powell";
            case 3 -> "Backtracking";
            case 4 -> "DSatur";
            default -> "No valido";
        };
    }
    
    // contar cada color unico de la lista de colores
    public static int contarColores(int[] listaColores) {
        HashSet<Integer> colores = new HashSet();
        for (int i = 0; i < listaColores.length; i++) {
            if(!colores.contains(listaColores[i])) {
                colores.add(listaColores[i]);
            }
        }
        return colores.size();
    }
    
    // convertir int del color en un color de Java
    public static Color getColorFromInt(int numColor) {
        return switch (numColor % 10) {
            case 0 -> Color.RED;
            case 1 -> Color.BLUE;
            case 2 -> Color.GREEN;
            case 3 -> Color.YELLOW;
            case 4 -> Color.ORANGE;
            case 5 -> Color.PINK;
            case 6 -> Color.CYAN;
            case 7 -> Color.MAGENTA;
            case 8 -> Color.GRAY;
            case 9 -> Color.BLACK;
            default -> Color.WHITE;
        };
    }    
    
    // 10 posiciones para nodos predeterminadas (osea solo funciona con grafos de hasta 10 vertices)
    private final Point[] posicionesNodo = {
        new Point(325, 50),
        new Point(550, 120),
        new Point(600, 275),
        new Point(550, 430),
        new Point(325, 500),
        new Point(100, 430),
        new Point(50, 275), 
        new Point(100, 120),
        new Point(450, 275), 
        new Point(250, 275)
    };    
    
    public MostrarGrafo(Grafo grafo, int[] resultado, int numAlgo) {
        initComponents();
        nombreAlgo = getNameAlgorithm(numAlgo);
        listaColores = resultado;
        grafoMuestra = grafo;
        tamañoGrafo = grafoMuestra.getSize();
        matrizAdyacencia = grafoMuestra.getMatrizAdyacencia();        
        listaNodos = grafoMuestra.getListaNodos();        
        cantColores = contarColores(listaColores);
        setBackground(WHITE); // fondo blanco inicial
        setPreferredSize(new Dimension(800, 600));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

@Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g; // libreria para graficos 2D

        if (tamañoGrafo == 0) {
            return;
        }
        
        // escribir titulo del algoritmo
        g2d.setFont(new Font("Arial", Font.BOLD, 20));
        g2d.setColor(Color.BLACK);
        g2d.drawString(nombreAlgo, 50, 20);
        g2d.drawString("N° de colores: "+String.valueOf(cantColores), 50, 40);
        
        // dibujar aristas en base al arreglo de posiciones
        for (int i = 0; i < tamañoGrafo; i++) {
            for (int j = i + 1; j < tamañoGrafo; j++) {
                if (matrizAdyacencia[i][j] == 1) { 
                    Point p1 = posicionesNodo[i];
                    Point p2 = posicionesNodo[j];
                    g2d.drawLine(p1.x, p1.y, p2.x, p2.y);
                }
            }
        }
        
        // dibujar vertices en base a la listaNodos
        for (int i = 0; i < tamañoGrafo; i++) {
            NodoGrafo nodo = listaNodos.get(i);
            Point pos = posicionesNodo[i];
            Color color = getColorFromInt(listaColores[i]);
            int x = pos.x - radioNodo;
            int y = pos.y - radioNodo;
            int diameter = 2 * radioNodo;

            // sacar el color de la lista de colores resultados del algoritmo
            g2d.setColor(color); 
            g2d.fillOval(x, y, diameter, diameter);

            // pintar borde de color negro
            g2d.setColor(Color.BLACK);
            g2d.drawOval(x, y, diameter, diameter);
            
            // imprimir nombre del vertice
            g2d.setFont(new Font("Arial", Font.BOLD, 12));
            g2d.setColor(Color.BLACK);
            int textX = pos.x - 12; 
            int textY = pos.y + 4;
            g2d.drawString(nodo.getData(), textX, textY);
        }
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
